### ISSUE TITLE
float64 -> integer conversion doesn't work

### ISSUE THREAD

**Issue by mwhudson** [4ad/go.arm64#42]
``` shellsession
mwhudson@narsil:go-test-cases$ cat exp.go
package p

func e(k int) float64 {
    return float64(k)
}
mwhudson@narsil:go-test-cases$ GOARCH=arm64 /opt/opensource/go/pkg/tool/linux_amd64/7g  exp.go 00024 (exp.go:4) SCVTFS  F7,F7
00024 (exp.go:4)    SCVTFS  F7,F7
exp.go:5: illegal combination 00024 (exp.go:4)  SCVTFS  F7,F7 FREG NONE FREG, 16 16
```

**Comment by minux** [comment]
Two problems here:
there is no ASCVTFS entry in optab, this is minor, just one line should fix
it:
{ ASCVTFS,      C_REG,  C_NONE, C_FREG,         29, 4, 0 },
(but why is it using SCVTFS instead of SCVTFD here? Remember to fix this
when you fix gmove.)

The other issue is that it's using 9g's gmove code. Power's integer unit and
floating point unit are completely separate, so to convert an integer to FP,
you need to load the integer into a FP register (through memory, there is no
way to transfer a integer register to a floating point register directly),
and then
do convert.

But ARM's FP is much saner: it provides both SCVTFS/D and UCVTFS/D, so
the algorithm could be much simplified.

The 2nd issue involves fixing gmove starting from line 915 of cmd/7g/gsubr.c.

**Comment by mwhudson** [comment]
Oh yes, I remember that Power detail.  Maybe this is a case where cribbing from 5g or 6g makes more sense...

**Comment by minux** [comment]
6g is too different. 5g doesn't implement 64-bit integer to/from floating
point
conversion.

arm64 provides all the required instructions for float/int conversions. it
should
be quite simple to use them in gmove.

**Comment by mwhudson** [comment]
To check my understanding, we can also simplify the games around TUINT64?  Because arm64 has "convert to unsigned double word, rounding towards zero" but ppc64 does not (only "convert to signed word, rounding towards zero", and "convert to unsigned double word, rounding as per fpscr")?

**Comment by mwhudson** [comment]
https://github.com/4ad/go/tree/integer-float-conversion has a start at this, I'll finish it up tomorrow and send a proper PR if noone beats me to it (it's not hard, but its new territory for me and things keep distracting me...)

**Comment by minux** [comment]
yes, I think we don't need any of the extra steps to convert between fp/int.
just emit the convert instruction first, and then optionally emit a
narrowing
instruction (for fp->int). Similar for int->fp. Use explicit enlarging move
to
convert to int64/uint64, and then use the conversion instruction.
(The explicit narrowing and enlarging step is necessary to maintain Go
semantics.)

For your integer-float-conversion patch:
ASCVTFD needs Conv bit in proginfo.

**Comment by mwhudson** [comment]
See #47
